### ISSUE TITLE
Update Failures due to Readiness Probes

### ISSUE THREAD

**Issue by carpenike** [halkeye-helm-charts/nzbhydra2-chart#4]
hi,

Curious how you handle updates of NzbHydra. A recent update took a little over 2 minutes for me (JVM was doing the update, 44 seconds to start the service once done).

`2019-12-19 16:35:55.050  INFO --- [           main] org.nzbhydra.NzbHydra                    : Started NzbHydra in 44.761 seconds (JVM running for 123.698)`

However, the helm chart has readiness probes defaulting at 10 seconds with 3 failures allowed before killing the pod:

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nzbhydra2
        ports:
        - containerPort: 5076
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
